# -*- coding: utf-8 -*-
"""MINIPROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaHKULD5a5ljKJEg7AxHy-gA_osovHOF

# Welcome to Colab!
"""

! pip install scanpy anndata pandas numpy
! pip install matplotlib seaborn scikit-learn
! pip install harmonypy GEOparse leidenalg python-igraph

import os, tarfile, glob
import numpy as np
import pandas as pd
import scipy.io
import scanpy as sc
import anndata as ad

DATA_DIR = "./data"
EXTRACT  = "./data/GSE157783_extracted"
os.makedirs(EXTRACT, exist_ok=True)

# ── Step 1: Verify all three files are present ───────────────
FILES = {
    "umi"  : "GSE157783_IPDCO_hg_midbrain_UMI.tar.gz",
    "cell" : "GSE157783_IPDCO_hg_midbrain_cell.tar.gz",
    "genes": "GSE157783_IPDCO_hg_midbrain_genes.tar.gz",
}

for key, fname in FILES.items():
    fpath = os.path.join(DATA_DIR, fname)
    if not os.path.exists(fpath):
        raise FileNotFoundError(
            f"Missing: {fpath}\n"
            "Download all three files from:\n"
            "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE157783\n"
            "and place them in ./data/"
        )
    print(f"  Found {fname}  ({os.path.getsize(fpath)//1000} KB)")

print("\nAll three files present — extracting ...")

# ── Step 2: Extract all three archives ──────────────────────
for key, fname in FILES.items():
    fpath = os.path.join(DATA_DIR, fname)
    with tarfile.open(fpath, "r:gz") as tar:
        tar.extractall(EXTRACT)
    print(f"  Extracted {fname}")

# ── Step 3: Inspect what we got ──────────────────────────────
# This is critical — we need to see the actual filenames
# before writing any loading code
all_extracted = []
for root, dirs, files in os.walk(EXTRACT):
    for f in files:
        full = os.path.join(root, f)
        rel  = os.path.relpath(full, EXTRACT)
        size = os.path.getsize(full)
        all_extracted.append((rel, size))
        print(f"  {rel}  ({size//1000} KB)")

# ── PEEK CELL — run this first, paste the output here ────────
# We need to know:
# 1. Is the UMI matrix  genes × cells  or  cells × genes?
# 2. Does the cell file contain condition/sample labels?
# 3. Does the genes file have one column or multiple?

import pandas as pd

UMI_PATH   = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_UMI.tsv"
CELL_PATH  = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_cell.tsv"
GENES_PATH = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_genes.tsv"

# ── Peek UMI matrix (just top-left corner) ───────────────────
print("=" * 55)
print("UMI FILE — first 4 rows, first 5 columns:")
print("=" * 55)
umi_peek = pd.read_csv(UMI_PATH, sep="\t", nrows=4, index_col=0)
print(f"Shape of peek : {umi_peek.shape}  (rows × cols shown)")
print(umi_peek.iloc[:4, :5])

# Count total rows and columns without loading full matrix
with open(UMI_PATH) as f:
    header     = f.readline()
    n_cols     = len(header.strip().split("\t"))
    n_rows     = sum(1 for _ in f)          # count remaining lines
print(f"\nActual full dimensions: {n_rows} rows  ×  {n_cols} cols (including index)")

# ── Peek cell metadata ────────────────────────────────────────
print("\n" + "=" * 55)
print("CELL FILE — first 5 rows, all columns:")
print("=" * 55)
cell_peek = pd.read_csv(CELL_PATH, sep="\t", nrows=5)
print(f"Columns : {list(cell_peek.columns)}")
print(cell_peek)

# ── Peek gene list ────────────────────────────────────────────
print("\n" + "=" * 55)
print("GENES FILE — first 10 rows:")
print("=" * 55)
genes_peek = pd.read_csv(GENES_PATH, sep="\t", nrows=10, header=None)
print(f"Columns in genes file: {genes_peek.shape[1]}")
print(genes_peek)

import os, tarfile
import numpy as np
import pandas as pd
import scipy.sparse as sp
import scanpy as sc
import anndata as ad

UMI_PATH   = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_UMI.tsv"
CELL_PATH  = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_cell.tsv"
GENES_PATH = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_genes.tsv"

# ── Step 1: Load gene metadata ────────────────────────────────
# Column 0 = Ensembl gene IDs, used as gene names in AnnData
print("Loading gene list ...")
genes_df = pd.read_csv(GENES_PATH, sep="\t", header=0)

# Column 0 is named 'gene' and contains Ensembl IDs
gene_ids = genes_df.iloc[:, 0].values.astype(str)
print(f"  Genes loaded : {len(gene_ids)}")
print(f"  Example IDs  : {gene_ids[:3]}")

# ── Step 2: Load cell metadata ────────────────────────────────
# Contains: barcode, cell_ontology (pre-annotated!), patient (e.g. PD3)
print("\nLoading cell metadata ...")
cell_df = pd.read_csv(CELL_PATH, sep="\t", header=0)
cell_df = cell_df.set_index("barcode")

# Infer condition from patient label
# e.g. "PD3" → PD,  "CTR2" / "CTRL2" / "CO1" → Control
def infer_condition(patient: str) -> str:
    p = str(patient).upper()
    if p.startswith("PD"):
        return "PD"
    if any(p.startswith(k) for k in ("CTR", "CTRL", "CO", "CON", "NORMAL", "HC")):
        return "Control"
    return "Unknown"

cell_df["condition"] = cell_df["patient"].apply(infer_condition)

print(f"  Cells loaded    : {len(cell_df)}")
print(f"  Columns         : {list(cell_df.columns)}")
print(f"\n  Condition counts:\n{cell_df['condition'].value_counts().to_string()}")
print(f"\n  Patient labels  : {sorted(cell_df['patient'].unique())}")
print(f"\n  Cell types found:\n{cell_df['cell_ontology'].value_counts().to_string()}")

import os
import numpy as np
import pandas as pd
import scipy.sparse as sp
import scanpy as sc
import anndata as ad

UMI_PATH   = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_UMI.tsv"
CELL_PATH  = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_cell.tsv"
GENES_PATH = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_genes.tsv"

# ── Step 1: Load gene + cell metadata (small files, fast) ─────
print("Loading gene list ...")
genes_df = pd.read_csv(GENES_PATH, sep="\t", header=0)
gene_ids = genes_df.iloc[:, 0].values.astype(str)
print(f"  {len(gene_ids)} genes")

print("Loading cell metadata ...")
cell_df = pd.read_csv(CELL_PATH, sep="\t", header=0)
cell_df = cell_df.set_index("barcode")

def infer_condition(patient):
    p = str(patient).upper()
    if p.startswith("PD"):
        return "PD"
    if any(p.startswith(k) for k in ("CTR","CTRL","CO","CON","HC","NORMAL")):
        return "Control"
    return "Unknown"

cell_df["condition"] = cell_df["patient"].apply(infer_condition)
print(f"  {len(cell_df)} cells")
print(cell_df["condition"].value_counts().to_string())

# ── Step 2: Read UMI in chunks → build sparse matrix ──────────
# Never loads full matrix into RAM
# Each chunk = 500 genes at a time → ~200 MB per chunk max
print("\nLoading UMI matrix in chunks (genes x cells) ...")
print("This will take 3-6 minutes but will NOT crash ...")

CHUNK_SIZE = 500   # genes per chunk — reduce to 200 if still slow

chunks      = []   # list of sparse matrices, one per chunk
gene_names  = []   # gene row index collected as we go
cell_names  = None # column names (cell barcodes) — read once

reader = pd.read_csv(
    UMI_PATH,
    sep       = "\t",
    index_col = 0,
    chunksize = CHUNK_SIZE,
    dtype     = np.float32   # float32 uses half the RAM of float64
)

total_genes_loaded = 0
for i, chunk in enumerate(reader):

    # Capture cell barcode names from first chunk only
    if cell_names is None:
        cell_names = chunk.columns.tolist()
        print(f"  Cell barcodes found : {len(cell_names)}")

    # Convert dense chunk → sparse immediately (before stacking)
    sparse_chunk = sp.csr_matrix(chunk.values)
    chunks.append(sparse_chunk)
    gene_names.extend(chunk.index.tolist())

    total_genes_loaded += chunk.shape[0]

    # Progress every 5 chunks
    if (i + 1) % 5 == 0:
        print(f"  Loaded {total_genes_loaded:,} / ~26,737 genes ...", flush=True)

# Stack all sparse chunks vertically → full genes x cells matrix
print("\nStacking chunks into full sparse matrix ...")
X_genes_x_cells = sp.vstack(chunks)          # shape: genes x cells
print(f"  Full shape (genes x cells) : {X_genes_x_cells.shape}")

# Transpose → cells x genes (AnnData format)
X_cells_x_genes = X_genes_x_cells.T.tocsr()
print(f"  Transposed (cells x genes) : {X_cells_x_genes.shape}")

# ── Step 3: Align cells ───────────────────────────────────────
print("\nAligning cell barcodes ...")
cell_names_series = pd.Index(cell_names)
common            = cell_names_series.intersection(cell_df.index)
print(f"  Cells in matrix   : {len(cell_names_series)}")
print(f"  Cells in metadata : {len(cell_df)}")
print(f"  Common cells      : {len(common)}")

if len(common) == 0:
    print("\n  UMI barcode sample  :", cell_names[:3])
    print("  Cell file sample    :", list(cell_df.index[:3]))
    raise ValueError("No matching barcodes — paste above samples and I will fix.")

# Reorder matrix rows to match common cells
cell_idx = [cell_names.index(c) for c in common]
X_final  = X_cells_x_genes[cell_idx, :]
meta     = cell_df.loc[common].copy()

# ── Step 4: Build AnnData ────────────────────────────────────
print("\nBuilding AnnData ...")
var_df           = pd.DataFrame(index=pd.Index(gene_names, name="gene_id"))
adata            = ad.AnnData(X=X_final, obs=meta, var=var_df)
adata.obs_names  = pd.Index(common)

print(f"\n{'─'*45}")
print(f"SUCCESS")
print(f"  Cells  : {adata.n_obs:,}")
print(f"  Genes  : {adata.n_vars:,}")
print(f"\n  Condition counts:")
print(adata.obs["condition"].value_counts().to_string())
print(f"\n  Cell types:")
print(adata.obs["cell_ontology"].value_counts().to_string())
print(f"{'─'*45}")

# Save checkpoint — never reload raw TSVs again after this
adata.write("/content/data/pd_raw_loaded.h5ad")
print("\nSaved: /content/data/pd_raw_loaded.h5ad")
print("Proceed to QC (Step 4)")

import scanpy as sc

adata = sc.read("/content/data/pd_raw_loaded.h5ad")
print(f"Loaded: {adata.n_obs:,} cells × {adata.n_vars:,} genes")

# ── Fix 1: Duplicate gene names ──────────────────────────────
# Ensembl IDs like ENSG00000xxx can appear twice if the original
# dataset had duplicated rows — make_unique appends -1, -2 etc.
adata.var_names_make_unique()
print(f"Gene names made unique")

# ── Fix 2: Mitochondrial genes — Ensembl ID lookup ───────────
# Our var_names are Ensembl IDs (ENSG...), not gene symbols
# MT- prefix only works for gene symbols like MT-ND1, MT-CO1
# For Ensembl IDs we use the known human mitochondrial gene list

# These are the 13 protein-coding mitochondrial Ensembl IDs
MT_ENSEMBL = {
    "ENSG00000198888", "ENSG00000198763", "ENSG00000198804",
    "ENSG00000198712", "ENSG00000228253", "ENSG00000198899",
    "ENSG00000198938", "ENSG00000198727", "ENSG00000198840",
    "ENSG00000212907", "ENSG00000198886", "ENSG00000198695",
    "ENSG00000198786"
}

adata.var["mt"] = adata.var_names.isin(MT_ENSEMBL)
print(f"Mitochondrial genes found: {adata.var['mt'].sum()}")

# ── QC metrics ───────────────────────────────────────────────
sc.pp.calculate_qc_metrics(
    adata, qc_vars=["mt"],
    percent_top=None, log1p=False, inplace=True
)

# ── Plot ─────────────────────────────────────────────────────
sc.pl.violin(adata,
    ["n_genes_by_counts", "total_counts", "pct_counts_mt"],
    jitter=0.4, multi_panel=True
)

print("\nGene count per cell:")
print(adata.obs["n_genes_by_counts"].describe().round(1))
print("\nMito % per cell:")
print(adata.obs["pct_counts_mt"].describe().round(3))

# snRNA-seq thresholds — slightly lower than scRNA-seq
# because nuclei naturally capture fewer genes than whole cells
before = adata.n_obs

sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_cells(adata, max_genes=6000)   # removes doublets
sc.pp.filter_genes(adata, min_cells=10)     # removes rarely detected genes

# Note: NO mitochondrial filter for snRNA-seq
# Nuclei have near-zero mito reads naturally — filtering on it
# would remove good cells

after = adata.n_obs
print(f"Before filtering : {before:,} cells")
print(f"After filtering  : {after:,} cells")
print(f"Removed          : {before - after:,} low quality cells")
print(f"Genes remaining  : {adata.n_vars:,}")

# Normalize each cell to 10,000 total counts
sc.pp.normalize_total(adata, target_sum=1e4)

# Log transform — reduces effect of highly expressed genes
sc.pp.log1p(adata)

# Save raw normalized values — needed later for differential expression
adata.raw = adata

# Save Day 1 final checkpoint
adata.write("/content/data/pd_day1_complete.h5ad")

print("Normalization complete")
print(f"Final AnnData: {adata.n_obs:,} cells × {adata.n_vars:,} genes")
print("\nDay 1 complete ✅")
print("Next: open a new cell and start Day 2")

import scanpy as sc

adata = sc.read("/content/data/pd_day1_complete.h5ad")

# MARINE ALGAE CONTINUATION STEP 1
import scanpy as sc
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample

# Load your final h5ad
adata = sc.read_h5ad('/content/data/pd_day1_complete.h5ad')

# Calculate highly variable genes
sc.pp.highly_variable_genes(adata, n_top_genes=2000)

# Use HVGs only (same as original RF training)
hvg_genes = adata.var_names[adata.var['highly_variable']].tolist()
X = adata[:, hvg_genes].X
if hasattr(X, 'toarray'):
    X = X.toarray()

# Encode cell type labels
le = LabelEncoder()
y = le.fit_transform(adata.obs['cell_ontology'])

# Balanced subsample (400 per class)
idx = []
for c in np.unique(y):
    ci = np.where(y == c)[0]
    chosen = resample(ci, n_samples=min(400, len(ci)), random_state=42)
    idx.extend(chosen)

X_bal = X[idx]
y_bal = y[idx]

# Train RF (same parameters as original)
rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_bal, y_bal)

# Extract and save top 20 feature importance genes
importances = pd.Series(rf.feature_importances_, index=hvg_genes)
top20 = importances.nlargest(20).reset_index()
top20.columns = ['gene_name', 'importance_score']
top20.to_csv('/content/data/top20_features.csv', index=False)

print("Top 20 Feature Importance Genes:")
print(top20.to_string(index=False))

##STEP 2
import requests
import time

top20 = pd.read_csv('/content/data/top20_features.csv')

def get_uniprot_and_pdb(gene_name, organism_id='9606'):
    """
    Query UniProt for human protein ID and associated PDB structures.
    9606 = Homo sapiens taxonomy ID
    """
    # Search UniProt
    url = f"https://rest.uniprot.org/uniprotkb/search"
    params = {
        'query': f'gene_exact:{gene_name} AND organism_id:{organism_id} AND reviewed:true',
        'format': 'json',
        'fields': 'accession,gene_names,protein_name,xref_pdb',
        'size': 1
    }
    try:
        r = requests.get(url, params=params, timeout=10)
        data = r.json()
        if data['results']:
            entry = data['results'][0]
            uniprot_id = entry['primaryAccession']
            # Extract PDB IDs
            pdb_ids = []
            for ref in entry.get('uniProtKBCrossReferences', []):
                if ref['database'] == 'PDB':
                    pdb_ids.append(ref['id'])
            return uniprot_id, pdb_ids[:3]  # Return top 3 PDB structures
        return None, []
    except Exception as e:
        print(f"  Error for {gene_name}: {e}")
        return None, []

# Map all top 20 genes
results = []
print(f"{'Gene':<12} {'UniProt':<12} {'PDB IDs'}")
print("-" * 50)

for _, row in top20.iterrows():
    gene = row['gene_name']
    uniprot_id, pdb_ids = get_uniprot_and_pdb(gene)
    results.append({
        'gene_name': gene,
        'importance_score': row['importance_score'],
        'uniprot_id': uniprot_id,
        'pdb_ids': ', '.join(pdb_ids) if pdb_ids else 'Not available'
    })
    print(f"{gene:<12} {str(uniprot_id):<12} {', '.join(pdb_ids) if pdb_ids else 'None'}")
    time.sleep(0.5)  # Respect API rate limit

# Save mapping table
target_df = pd.DataFrame(results)
target_df.to_csv('/content/data/gene_target_mapping.csv', index=False)
print("\nSaved: gene_target_mapping.csv")

import requests

# Your four algae and their known bioactive compounds
algal_compounds = {
    'Ecklonia_cava':             ['Phloroglucinol', 'Dieckol', 'Phlorofucofuroeckol A'],
    'Phaeodactylum_tricornutum': ['Fucoxanthin', 'Fucoxanthinol'],
    'Haematococcus_pluvialis':   ['Astaxanthin', 'Canthaxanthin'],
    'Chlamydomonas_reinhardtii': ['Beta-carotene', 'Lutein']
}

def get_smiles(compound_name):
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{compound_name}/property/IsomericSMILES,MolecularWeight,MolecularFormula/JSON"
    try:
        r = requests.get(url, timeout=10)
        data = r.json()
        prop = data['PropertyTable']['Properties'][0]
        return {
            'compound': compound_name,
            'smiles': prop.get('IsomericSMILES', ''),
            'mol_weight': prop.get('MolecularWeight', ''),
            'formula': prop.get('MolecularFormula', '')
        }
    except:
        return {'compound': compound_name, 'smiles': None, 'mol_weight': None, 'formula': None}

# Fetch all compounds
compound_records = []
print(f"{'Algae':<35} {'Compound':<30} {'MW':<10} {'SMILES (truncated)'}")
print("-" * 100)

for algae, compounds in algal_compounds.items():
    for cmpd in compounds:
        result = get_smiles(cmpd)
        result['algae_source'] = algae
        compound_records.append(result)
        smiles_preview = (result['smiles'] or 'Not found')[:40] + '...'
        print(f"{algae:<35} {cmpd:<30} {str(result['mol_weight']):<10} {smiles_preview}")
        time.sleep(0.3)

# Save
compounds_df = pd.DataFrame(compound_records)
compounds_df.dropna(subset=['smiles'], inplace=True)
compounds_df.to_csv('/content/data/algal_compounds_smiles.csv', index=False)
print(f"\nSaved: {len(compounds_df)} compounds with valid SMILES")



sc.pp.highly_variable_genes(adata, min_mean=0.0125,
    max_mean=3, min_disp=0.5)
print(f"HVGs selected: {adata.var.highly_variable.sum()}")
sc.pl.highly_variable_genes(adata)
adata = adata[:, adata.var.highly_variable]

import scanpy as sc

sc.pp.scale(adata, max_value=10)
sc.tl.pca(adata, svd_solver='arpack')
sc.pl.pca_variance_ratio(adata, log=True, n_pcs=50)

import scanpy as sc
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)
sc.tl.leiden(adata, resolution=0.5)
print(f"Clusters found: {adata.obs['leiden'].nunique()}")

sc.tl.umap(adata)
sc.pl.umap(adata, color=['leiden'],
           palette='tab10', frameon=False,
           title='Cell clusters')

import scanpy as sc

# Overlay the pre-annotated cell types onto your UMAP
sc.pl.umap(adata,
    color="cell_ontology",
    legend_loc="on data",
    legend_fontsize=8,
    frameon=False,
    title="Cell types — PD midbrain snRNA-seq"
)

sc.pl.umap(adata,
    color           = "cell_ontology",
    legend_loc      = "right margin",
    legend_fontsize = 11,
    frameon         = False,
    title           = "Cell Types — PD Midbrain snRNA-seq"
)

plt.savefig("/content/clean_celltypes_umap.png",
    dpi=200, bbox_inches="tight", facecolor="white")
print("Saved — download from Files panel")

# Check condition distribution first
print(adata.obs["condition"].value_counts())

# Plot PD vs Control on same UMAP
sc.pl.umap(adata,
    color="condition",
    palette={"PD": "#D85A30", "Control": "#185FA5", "Unknown": "#AAAAAA"},
    frameon=False,
    title="PD vs Control — midbrain nuclei"
)

print("All unique patient labels in dataset:")
print(adata.obs["patient"].unique())
print("\nCondition counts:")
print(adata.obs["condition"].value_counts())

# Fix condition labels directly from patient names
# PD1-PD5 → PD,  C1-C6 → Control
adata.obs["condition"] = adata.obs["patient"].apply(
    lambda p: "PD" if str(p).startswith("PD") else "Control"
)

# Verify
print("Fixed condition counts:")
print(adata.obs["condition"].value_counts())
print("\nPatient → Condition mapping:")
print(adata.obs[["patient","condition"]].drop_duplicates().sort_values("patient"))

# Replot immediately
import scanpy as sc
sc.pl.umap(adata,
    color="condition",
    palette={"PD":"#D85A30","Control":"#185FA5"},
    frameon=False,
    title="PD vs Control — midbrain nuclei"
)

sc.pl.umap(adata,
    color="cell_ontology",
    legend_loc="on data",
    legend_fontsize=7,
    frameon=False,
    title="Cell types — PD midbrain snRNA-seq"
)

adata.write("/content/data/pd_day2_complete.h5ad")
print("Day 2 complete ✅")
print(f"Cells : {adata.n_obs:,}")
print(f"Genes : {adata.n_vars:,}")
print("\nUMAP plots generated:")
print("  1. Cell clusters (21 clusters)")
print("  2. Cell types (cell_ontology)")
print("  3. PD vs Control condition")
print("\nProceed to Day 3 — ML classifier")

import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import scipy.sparse as sp
import warnings
warnings.filterwarnings("ignore")

adata = sc.read("/content/data/pd_day2_complete.h5ad")
print(f"Loaded: {adata.n_obs:,} cells × {adata.n_vars:,} genes")

# Check what cell types exist — pick the most relevant for PD
print("\nCell types available:")
print(adata.obs["cell_ontology"].value_counts())

print("\nCondition counts:")
print(adata.obs["condition"].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# ── Fix 1: Re-apply condition fix on loaded data ──────────────
# The day2 checkpoint was saved before the condition fix
# Re-apply it now
adata.obs["condition"] = adata.obs["patient"].apply(
    lambda p: "PD" if str(p).startswith("PD") else "Control"
)
print("Condition fix re-applied:")
print(adata.obs["condition"].value_counts())

# ── Redo DaN subset with correct labels ───────────────────────
dan = adata[adata.obs["cell_ontology"] == "DaNs"].copy()
print(f"\nDaN breakdown (corrected):")
print(dan.obs["condition"].value_counts())

# ── Fix 2: Per-donor DaN proportion ──────────────────────────
rows = []
for donor in adata.obs["patient"].unique():
    donor_cells = adata.obs[adata.obs["patient"] == donor]
    condition   = donor_cells["condition"].iloc[0]
    total       = len(donor_cells)
    n_dan       = (donor_cells["cell_ontology"] == "DaNs").sum()
    pct         = n_dan / total * 100
    rows.append({"patient": donor, "condition": condition,
                 "DaN_count": n_dan, "DaN_pct": pct})

per_donor = pd.DataFrame(rows).sort_values("condition")
print("\nPer-donor DaN counts:")
print(per_donor.to_string(index=False))

# ── Fix 3: Updated seaborn syntax (no palette deprecation) ────
fig, ax = plt.subplots(figsize=(6, 4))

sns.boxplot(
    data    = per_donor,
    x       = "condition",
    y       = "DaN_pct",
    hue     = "condition",          # fixes palette deprecation
    palette = {"PD":"#D85A30", "Control":"#185FA5"},
    legend  = False,
    ax      = ax
)
sns.stripplot(
    data    = per_donor,
    x       = "condition",
    y       = "DaN_pct",
    hue     = "condition",
    palette = {"PD":"#D85A30", "Control":"#185FA5"},
    legend  = False,
    size    = 8,
    color   = "black",
    ax      = ax
)

ax.set_ylabel("DaN % of total nuclei per donor")
ax.set_xlabel("Condition")
ax.set_title("Dopaminergic Neuron Proportion\nPD vs Control — Human Midbrain snRNA-seq")
plt.tight_layout()
plt.savefig("/content/data/DaN_proportion.png", dpi=150)
plt.show()
print("Plot saved.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (classification_report,
    roc_auc_score, confusion_matrix, roc_curve)
import scipy.sparse as sp
import warnings
warnings.filterwarnings("ignore")

# ── Select HVGs for ML features ───────────────────────────────
import scanpy as sc
sc.pp.highly_variable_genes(adata, n_top_genes=2000)
hvg_names = adata.var_names[adata.var["highly_variable"]].tolist()
print(f"HVGs selected : {len(hvg_names)}")

# ── Balanced subsample ────────────────────────────────────────
pd_idx  = adata.obs[adata.obs["condition"] == "PD"].index
ct_idx  = adata.obs[adata.obs["condition"] == "Control"].index
n_each  = min(4000, len(pd_idx), len(ct_idx))

rng      = np.random.default_rng(42)
pd_samp  = rng.choice(pd_idx, n_each, replace=False)
ct_samp  = rng.choice(ct_idx, n_each, replace=False)
keep     = np.concatenate([pd_samp, ct_samp])

sub = adata[keep, hvg_names].copy()
print(f"Subsampled    : {sub.n_obs:,} cells × {sub.n_vars:,} HVGs")
print(sub.obs["condition"].value_counts())

# ── Build X and y ─────────────────────────────────────────────
X = sub.X.toarray() if sp.issparse(sub.X) else sub.X.copy()
y = (sub.obs["condition"] == "PD").astype(int).values

# ── 5-fold cross validation ───────────────────────────────────
print("\nTraining Random Forest — 5-fold CV ...")
clf = RandomForestClassifier(
    n_estimators = 200,
    max_depth    = 15,
    random_state = 42,
    n_jobs       = -1
)

skf      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
aucs, tprs, mean_fpr = [], [], np.linspace(0, 1, 100)

for fold, (tr, te) in enumerate(skf.split(X, y)):
    clf.fit(X[tr], y[tr])
    proba    = clf.predict_proba(X[te])[:, 1]
    auc      = roc_auc_score(y[te], proba)
    aucs.append(auc)
    fpr, tpr, _ = roc_curve(y[te], proba)
    tprs.append(np.interp(mean_fpr, fpr, tpr))
    print(f"  Fold {fold+1} AUC : {auc:.3f}")

print(f"\nMean AUC : {np.mean(aucs):.3f} ± {np.std(aucs):.3f}")

# ── ROC curve ─────────────────────────────────────────────────
mean_tpr    = np.mean(tprs, axis=0)
mean_tpr[0] = 0.0

fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(mean_fpr, mean_tpr, color="#D85A30", lw=2,
    label=f"Mean ROC (AUC = {np.mean(aucs):.3f} ± {np.std(aucs):.3f})")
ax.fill_between(mean_fpr,
    np.mean(tprs, axis=0) - np.std(tprs, axis=0),
    np.mean(tprs, axis=0) + np.std(tprs, axis=0),
    alpha=0.2, color="#D85A30")
ax.plot([0,1],[0,1],"k--", lw=1, label="Random classifier")
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curve — PD vs Control Classifier\n(Random Forest, 5-fold CV)")
ax.legend(loc="lower right")
plt.tight_layout()
plt.savefig("/content/data/roc_curve.png", dpi=150)
plt.show()

# Train final model on full subset
print("Training final model ...")
clf.fit(X, y)

importances = pd.Series(
    clf.feature_importances_,
    index=hvg_names
).sort_values(ascending=False)

top20 = importances.head(20)

fig, ax = plt.subplots(figsize=(8, 6))
colors  = ["#D85A30"] * 5 + ["#185FA5"] * 15
top20[::-1].plot(kind="barh", ax=ax,
    color=colors[::-1])
ax.set_xlabel("Feature Importance")
ax.set_title("Top 20 Genes — PD vs Control\nRandom Forest Classifier")
ax.axvline(importances.mean(), color="gray",
    linestyle="--", lw=1, label="Mean importance")
ax.legend()
plt.tight_layout()
plt.savefig("/content/data/feature_importance.png", dpi=150)
plt.show()

print("\nTop 10 genes:")
print(top20.head(10).round(5).to_string())

# Final predictions
y_pred = clf.predict(X)
cm     = confusion_matrix(y, y_pred)

fig, ax = plt.subplots(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
    xticklabels=["Control","PD"],
    yticklabels=["Control","PD"], ax=ax)
ax.set_xlabel("Predicted")
ax.set_ylabel("Actual")
ax.set_title("Confusion Matrix — PD vs Control")
plt.tight_layout()
plt.savefig("/content/data/confusion_matrix.png", dpi=150)
plt.show()

print(classification_report(y, y_pred,
    target_names=["Control","PD"]))

# ── Final project summary ─────────────────────────────────────
print("\n" + "="*52)
print("  PROJECT COMPLETE — SUMMARY")
print("="*52)
print(f"  Dataset       : GSE157783 Human PD Midbrain")
print(f"  Technology    : snRNA-seq (10x Genomics)")
print(f"  Total nuclei  : {adata.n_obs:,}")
print(f"  Donors        : 5 PD  |  6 Control")
print(f"  Clusters      : 21")
print(f"  Cell types    : {adata.obs['cell_ontology'].nunique()}")
print(f"  DaNs found    : 47  (0.119% of nuclei)")
print(f"  ML AUC        : {np.mean(aucs):.3f} ± {np.std(aucs):.3f}")
print(f"  Top gene      : {top20.index[0]}")
print("="*52)
print("\nFigures saved:")
print("  DaN_proportion.png")
print("  roc_curve.png")
print("  feature_importance.png")
print("  confusion_matrix.png")

adata.write("/content/data/pd_final.h5ad")
print("\nFinal AnnData saved: pd_final.h5ad")
print("\nDay 3 complete ✅  Project complete ✅")

# Check what the original genes file actually contains
import pandas as pd

GENES_PATH = "/content/data/GSE157783_extracted/IPDCO_hg_midbrain_genes.tsv"
genes_df   = pd.read_csv(GENES_PATH, sep="\t", header=0)
print("Genes file columns:", list(genes_df.columns))
print("\nFirst 5 rows:")
print(genes_df.head())
print(f"\nTotal genes: {len(genes_df)}")

# ── Final viva summary printout ───────────────────────────────
print("=" * 55)
print("  FINAL PROJECT RESULTS")
print("=" * 55)
print()
print("  DATASET")
print(f"    Accession   : GSE157783")
print(f"    Tissue      : Human substantia nigra midbrain")
print(f"    Technology  : snRNA-seq (10x Genomics)")
print(f"    Donors      : 5 PD  |  6 Control")
print(f"    Nuclei      : {adata.n_obs:,} (after QC)")
print(f"    Genes       : {adata.n_vars:,}")
print()
print("  CLUSTERING")
print(f"    Algorithm   : Leiden (resolution 0.5)")
print(f"    Clusters    : 21")
print(f"    Cell types  : {adata.obs['cell_ontology'].nunique()}")
print()
print("  KEY BIOLOGICAL FINDING")
print(f"    DaNs found  : 47 nuclei (0.119% of total)")
print(f"    Implication : Near-complete DA neuron loss")
print(f"                  consistent with PD pathology")
print()
print("  ML CLASSIFIER")
print(f"    Model       : Random Forest (200 trees)")
print(f"    Features    : 2000 highly variable genes")
print(f"    Validation  : 5-fold stratified CV")
print(f"    Mean AUC    : 0.898 ± 0.005")
print(f"    Conclusion  : Gene expression alone can")
print(f"                  distinguish PD from Control")
print(f"                  nuclei with ~90% accuracy")
print()
print("  FIGURES")
print("    1. UMAP — 21 cell clusters")
print("    2. UMAP — cell type annotation")
print("    3. UMAP — PD vs Control distribution")
print("    4. DaN proportion boxplot (PD vs Control)")
print("    5. ROC curve (AUC = 0.898)")
print("    6. Feature importance — top 20 genes")
print("    7. Confusion matrix")
print("=" * 55)
print("\nProject complete ✅")

# Download all your project figures at once
from google.colab import files
import os

# List of all figures to download
figure_paths = [
    "/content/clean_celltypes_umap.png",          # Fig 5.3 — cell types
    "/content/data/DaN_proportion.png",            # Fig 5.5 — DaN boxplot
    "/content/data/roc_curve.png",                 # Fig 5.6 — ROC curve
    "/content/data/feature_importance.png",        # Fig 5.7 — feature importance
    "/content/data/confusion_matrix.png",          # Fig 5.8 — confusion matrix
]

# Download each file that exists
for path in figure_paths:
    if os.path.exists(path):
        print(f"Downloading: {path}")
        files.download(path)
    else:
        print(f"NOT FOUND: {path} — regenerate this plot first")

print("\nDone — check your browser Downloads folder")