# -*- coding: utf-8 -*-
"""scRNA-SEQ MELANOMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyRxmP4y8nA80c5N14Cns8kkYZhUYYdp
"""

# Install packages
! pip install scanpy leidenalg igraph -q

import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Scanpy version:", sc.__version__)

"""download GSE72056 data:"""

import urllib.request
import os

# Download GSE72056 matrix file
url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE72nnn/GSE72056/suppl/GSE72056_melanoma_single_cell_revised_v2.txt.gz"
urllib.request.urlretrieve(url, "GSE72056_melanoma.txt.gz")

print("Downloaded!")

"""Now load and inspect:"""

import gzip

# Load data
df = pd.read_csv("GSE72056_melanoma.txt.gz", sep="\t", index_col=0)
print(df.shape)
print(df.iloc[:5, :5])

"""Data loaded. First 3 rows = metadata, rest = gene expression. Separate them"""

# Extract metadata (first 3 rows)
metadata = df.iloc[:3, :].T
metadata.columns = ["tumor_id", "malignant", "cell_type"]
metadata = metadata.reset_index().rename(columns={"index": "cell"})

# Extract expression matrix (rows 3 onwards)
expr = df.iloc[3:, :]

# Transpose for scanpy (cells x genes)
expr_T = expr.T

print("Metadata:", metadata.shape)
print("Expression:", expr_T.shape)
print(metadata["malignant"].value_counts())

import anndata as ad

# Create AnnData object
adata = ad.AnnData(X=expr_T.values.astype(float))
adata.obs_names = expr_T.index
adata.var_names = expr_T.columns

# Add metadata
adata.obs["tumor_id"] = metadata["tumor_id"].values
adata.obs["malignant"] = metadata["malignant"].values
adata.obs["cell_type_num"] = metadata["cell_type"].values

# Map cell type numbers to names
cell_type_map = {1.0:"T_cell", 2.0:"B_cell", 3.0:"Macrophage",
                 4.0:"Endothelial", 5.0:"CAF", 6.0:"NK", 0.0:"Unresolved"}
adata.obs["cell_type"] = adata.obs["cell_type_num"].map(cell_type_map)

print(adata)
print(adata.obs["cell_type"].value_counts())

"""AnnData created. Now QC + preprocessing:"""

# QC metrics
sc.pp.calculate_qc_metrics(adata, inplace=True)

# Filter low quality cells
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

print("After QC:", adata.shape)

# Normalize
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

# Highly variable genes
sc.pp.highly_variable_genes(adata, n_top_genes=2000)
print("HVGs:", adata.var["highly_variable"].sum())

"""Fix duplicate var names then continue:"""

# Fix duplicate gene names
adata.var_names_make_unique()

# PCA
sc.pp.scale(adata, max_value=10)
sc.tl.pca(adata, svd_solver='arpack', n_comps=50)

# Neighbors + UMAP
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)
sc.tl.umap(adata)

# Leiden clustering
sc.tl.leiden(adata, resolution=0.5)

print("Clusters:", adata.obs["leiden"].nunique())

"""20 clusters found. Now visualize"""

# UMAP plots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sc.pl.umap(adata, color="leiden", ax=axes[0], show=False, title="Leiden Clusters")
sc.pl.umap(adata, color="cell_type", ax=axes[1], show=False, title="Cell Types")
sc.pl.umap(adata, color="malignant", ax=axes[2], show=False, title="Malignant Status")

plt.tight_layout()
plt.savefig("GSE72056_UMAP.png", dpi=300, bbox_inches="tight")
plt.show()
print("Done!")

"""marker gene dot plot:"""

# Marker genes per cell type
markers = {
    "T_cell": ["CD3D", "CD3E", "CD8A"],
    "B_cell": ["CD19", "MS4A1", "CD79A"],
    "Macrophage": ["CD68", "CSF1R", "AIF1"],
    "Endothelial": ["PECAM1", "VWF"],
    "CAF": ["FAP", "COL1A1"],
    "NK": ["NKG7", "GNLY"],
    "Malignant": ["MLANA", "MITF", "DCT"]
}

# Flatten marker list
all_markers = [g for genes in markers.values() for g in genes]

sc.pl.dotplot(adata, all_markers, groupby="cell_type",
              save="_GSE72056_markers.png", show=False)
print("Done!")

from google.colab import files
files.download("figures/dotplot__GSE72056_markers.png")

"""Random Forest classifier"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Use only annotated cells (not unresolved)
mask = adata.obs["cell_type"] != "Unresolved"
adata_filt = adata[mask]

# Get HVG expression matrix
hvg_genes = adata_filt.var_names[adata_filt.var["highly_variable"]]
X = adata_filt[:, hvg_genes].X
y = adata_filt.obs["cell_type"].values

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Train RF
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)

# Evaluate
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=rf.classes_)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=rf.classes_,
            yticklabels=rf.classes_, cmap="Blues")
plt.title("Random Forest — Confusion Matrix")
plt.ylabel("True")
plt.xlabel("Predicted")
plt.tight_layout()
plt.savefig("GSE72056_RF_confusion.png", dpi=300)
plt.show()

# Feature importance
feat_imp = pd.Series(rf.feature_importances_, index=hvg_genes)
top_features = feat_imp.sort_values(ascending=False).head(20)

plt.figure(figsize=(8, 6))
top_features.plot(kind="barh", color="#d62728")
plt.title("Top 20 Feature Importances — RF Classifier")
plt.xlabel("Importance")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("GSE72056_RF_features.png", dpi=300)
plt.show()
print("Done!")

# Save results
import pickle

# Save RF model
with open("GSE72056_RF_model.pkl", "wb") as f:
    pickle.dump(rf, f)

# Save AnnData
adata.write("GSE72056_adata.h5ad")

# Download all outputs
from google.colab import files
files.download("GSE72056_UMAP.png")
files.download("GSE72056_RF_confusion.png")
files.download("GSE72056_RF_features.png")
files.download("figures/dotplot__GSE72056_markers.png")

print("All saved!")